name: music_visualizer
description: this plugin help developers to show a music wave through animation.
version: 1.0.0
homepage: "https://github.com/Rajkumar07793/music_visualizer_package.git"


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.1"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter: